//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidAskBox.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BidAskBox.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USDCAD,01/10/2012 02:00:00.837,1.01903,1.01933
        ///USDJPY,01/10/2012 02:00:00.837,76.808,76.828
        ///AUDUSD,01/10/2012 02:00:00.837,1.03046,1.03066
        ///AUDUSD,01/10/2012 02:00:01.197,1.03047,1.03067
        ///GBPUSD,01/10/2012 02:00:01.197,1.54744,1.54774
        ///USDCAD,01/10/2012 02:00:01.197,1.01902,1.01932
        ///USDCHF,01/10/2012 02:00:01.197,0.94767,0.94797
        ///EURUSD,01/10/2012 02:00:01.197,1.27839,1.27856
        ///USDCHF,01/10/2012 02:00:01.540,0.9477,0.948
        ///EURUSD,01/10/2012 02:00:01.540,1.27837,1.27854
        ///GBPUSD,01/10/2012 02:00:01.837,1.5474 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ticks20120102 {
            get {
                return ResourceManager.GetString("Ticks20120102", resourceCulture);
            }
        }
    }
}
